### ISSUE TITLE
Time performance

### ISSUE THREAD

**Issue by nicolas-mng** [YefanZhou/TempBalance#1]
Hello,
Great paper and thank you for making your code available to everyone!
I gave it a go today and it seems to be quite slow unfortunately (20x slower than regular optimizers). Is it what you've been observing too? I have tested it with models with 100M parameters. Maybe I am not in the correct regime?

I apply it at every step, maybe I should really think this as a LR scheduler and only apply it every (let's say) 100 steps for example? The readme suggests doing it at the end of the epoch only.

**Comment by YefanZhou** [comment]
Hi! Our current method is developed as an epoch-wise LR scheduler, e.g., in the experiment [examples](https://github.com/YefanZhou/TempBalance/tree/main#compare-tempbalance-tb-to-cal-and-snr), it applies every epoch (about 390 steps for CIFAR100), and it only incurs about 5% time increment, and give the performance reported in the paper.

The step-wise updating can be slow, and you can update every 100 steps. To achieve a similar effect as the epoch-wise update, you can keep the learning rates unchanged between two updates.

**Comment by nicolas-mng** [comment]
Hello, thanks for the clarification! :)
